services:
  web-impersonate:
    image: web-impersonate
    build:
      context: .
    volumes:
      - ./nginx:/mnt/nginx
    environment:
        CMD: ${CMD:-tail -f /dev/null}
        DISPLAY: ${DISPLAY:-:99}
        SCREEN_RESOLUTION: ${SCREEN_RESOLUTION:-1920x1080}
        SCREEN_DEPTH: ${SCREEN_DEPTH:-24}
        START_LAVINMQ: ${START_LAVINMQ:-false}
        START_VNC: ${START_VNC:-false}
        START_XVBF: ${START_XVBF:-false}
        START_NGINX: ${START_NGINX:-false}
        START_HAPROXY: ${START_HAPROXY:-false}
    ports:
      - "5900:5900" # vnc
      - "15672:15672" # lavinmq
      - "5671:5671" # lavinmq
      - "5672:5672" # lavinmq
      - "3456:3456" # nginx
