name: 'Push linux/amd64 image'

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GAR_LOCATION: us-east1
  IMAGE_NAME: web-impersonate
  IMAGE_NAME_CACHE: web-impersonate-cache
  REPOSITORY: web-impersonate

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-build-publish-deploy:
    name: Push image
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set env
      run: echo "COMMIT_COUNT_TAG=$(git rev-list HEAD | wc -l | sed 's/^ *//g')" >> $GITHUB_ENV

    - name: Test env
      run: echo $COMMIT_COUNT_TAG

    - id: 'auth'
      uses: 'google-github-actions/auth@v0.6.0'
      with:
        credentials_json: '${{ secrets.ACCESS_TOKEN }}'
        token_format: 'access_token'

    - uses: 'docker/login-action@v1'
      name: 'Docker login'
      with:
        registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Create a new builder instance
    - name: Create builder
      run: docker buildx create --use --name amd64builder

    # Inspect the builder
    - name: Inspect builder
      run: docker buildx inspect --bootstrap --builder amd64builder

    # Build the Docker image for multiple platforms
    - name: Build and push
      run: |-
        docker buildx build \
          --builder amd64builder \
          --platform linux/amd64 \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ env.COMMIT_COUNT_TAG }}" \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest" \
          --cache-from=type=registry,ref=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME_CACHE \
          --cache-to=type=registry,ref=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME_CACHE,mode=max \
          --push \
          .